# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QDialog(object):
    def setupUi(self, QDialog):
        QDialog.setObjectName("QDialog")
        QDialog.resize(324, 249)
        self.verticalLayout = QtWidgets.QVBoxLayout(QDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sa_info_box = QtWidgets.QScrollArea(QDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sa_info_box.setFont(font)
        self.sa_info_box.setWidgetResizable(True)
        self.sa_info_box.setObjectName("sa_info_box")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 304, 229))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.vl_info_box = QtWidgets.QVBoxLayout()
        self.vl_info_box.setObjectName("vl_info_box")
        self.verticalLayout_2.addLayout(self.vl_info_box)
        self.sa_info_box.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.sa_info_box)

        self.retranslateUi(QDialog)
        QtCore.QMetaObject.connectSlotsByName(QDialog)

    def retranslateUi(self, QDialog):
        _translate = QtCore.QCoreApplication.translate
        QDialog.setWindowTitle(_translate("QDialog", "Dialog"))
